### ISSUE TITLE
Chords

### ISSUE THREAD

**Issue by SebAlbert** [sbngross/sk8erboi#2]
I just sat down by my piano with YouTube on 0.25 speed and figured ;)

Beginning seems correct, D major key, chords being D major, A major, B minor, Bb major, but then it doesn't repeat exactly, because in measue 8 you are badly clashing the B from the melody (which seems correct to me) with your Bb chord notes. I think it's C major here.

Then for the chorus I think you should make a key signature change instead of using accidentals over the place. The entire song shifts to F major here.
The chords then seem to be F major, C major, Bb major, A major; repeat. Finally Bb major ("earth"). (which you all have correct, I think, but maybe you want to add thirds from some of those chords?)

**Comment by sbngross** [comment]
You're right. My partner already agreed that there might a key change, because the C doesnt fit well in D major key.
The Karaoke midi and piano samples we found just had perfect 5fith's. The addition of thirds (maybe as part of an alternative lead melody) is currently on their way in another branch.

**Comment by SebAlbert** [comment]
Yes, C major in measures 8 and 16 is preparing the key change towards F major in the chorus :)

You may not need thirds everywhere, just try and see what sounds good.

**Comment by sbngross** [comment]
I'll keep the Bb Chord in 16 for now because it sounds right to me, ia. not too wrong.
The keys have been fixed.
